am335x: evm: add missing header include
gpio related warning is seen during compilation due to missing header

evm.c:714:4: warning: implicit declaration of function 'gpio_request'
evm.c:715:4: warning: implicit declaration of function
		'gpio_direction_output'

Fix this by adding proper include file (asm/gpio.h)

Signed-off-by: Hebbar, Gururaja <gururaja.hebbar@ti.com>
Tested-by: Satyanarayana, Sandhya <sandhya.satyanarayana@ti.com>