Do not initialize fastboot for SPL build
Commit a09faba618d176cc7c31e598102cb417b7c56efb causes the build for am335x_evm
to fail with the following error when building SPL:
    board/ti/am335x/evm.c:894: undefined reference to `fastboot_flash_add_ptn'

Fastboot initialization should not be part of SPL build,
so put it under #ifndef CONFIG_SPL_BUILD for am335x_evm and omap3evm

Signed-off-by: Vishveshwar Bhat <vishveshwar.bhat@ti.com>